steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:TAG', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:TAG']

  # Step 3: Deploy the Docker image to Google Cloud Run with environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'SERVICE_NAME',
      '--image', 'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:TAG',
      '--region', 'REGION',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'ENV_VAR1=VALUE1,ENV_VAR2=VALUE2'
    ]

images:
  - 'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:TAG'